# Generated by Django 5.1.2 on 2024-10-17 01:42

import django.db.models.deletion
import patrocars.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Montadora',
            fields=[
                ('id', patrocars.models.ULIDField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('ano_fundacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelosDeVeiculos',
            fields=[
                ('id', patrocars.models.ULIDField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('valor_referencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motorizacao', models.DecimalField(decimal_places=2, max_digits=4)),
                ('turbo', models.BooleanField(default=False)),
                ('automatico', models.BooleanField(default=False)),
                ('montadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrocars.montadora')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', patrocars.models.ULIDField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('cor', models.CharField(max_length=50)),
                ('ano_fabricacao', models.IntegerField()),
                ('ano_modelo', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('vendido', models.BooleanField(default=False)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrocars.modelosdeveiculos')),
            ],
        ),
    ]
